### ISSUE TITLE
初回コードレビュー

### ISSUE THREAD

**Issue by shibatadaiki** [ysk1180/jobmiru#1]

**Comment by shibatadaiki** [comment]
とりあえずREADMEに最低限の説明があると良いかもです！
（人に見せるのであればなおさら）

![2018-01-30 13 28 31](https://user-images.githubusercontent.com/25131575/35548263-9c3a0b7c-05c1-11e8-973d-6d22126c5be0.png)

**Comment by shibatadaiki** [comment]
https://github.com/ysk1180/jobmiru/blob/master/Gemfile
Gemfileはいらないコメントを決して、グループ単位でgemの記述場所を整えてあげると良いです。

![2018-01-30 13 31 59](https://user-images.githubusercontent.com/25131575/35548325-09530ea2-05c2-11e8-8d1a-665366a7415f.png)

**Comment by shibatadaiki** [comment]
コミットメッセージは他人から見て、そのコミットがどのような機能を追加したのかが一目でわかるような記述が望ましいです！

![2018-01-30 13 33 50](https://user-images.githubusercontent.com/25131575/35548361-3fcc8468-05c2-11e8-9432-cefbbb760ce0.png)

**Comment by shibatadaiki** [comment]
下記例

![2018-01-30 13 44 14](https://user-images.githubusercontent.com/25131575/35548571-b1d14872-05c3-11e8-977a-a58d75eb6940.png)

**Comment by shibatadaiki** [comment]
# Prevent CSRF attacks by raising an exception.

後こういういらないコメントは消しても良いかもです〜
（ただしconfigは消さなくて良いです）

**Comment by shibatadaiki** [comment]
https://github.com/ysk1180/jobmiru/blob/master/app/controllers/comment_to_posts_controller.rb
こういうのとかも

```
  # GET /comment_to_posts
  # GET /comment_to_posts.json

# binding.pry
```

**Comment by shibatadaiki** [comment]
```
format.json { render :show, status: :ok, location: @comment_to_post }
```

jsonの機能を使わないのであればjsonはこういった記述も削除しましょう。
（基本的に、使うもの以外の余分な記述はバグや誤解の温床になるので必要なもの以外は常に消しておく感じでお願いします）

**Comment by shibatadaiki** [comment]
https://github.com/ysk1180/jobmiru/blob/master/app/controllers/like_to_posts_controller.rb
これちょっとわかりづらいかも・・・？
（好みの問題かもしれないので要修正という感じではないです。ただ、一度決めた記述は基本的にどのコントローラでも共通してそれを使う感じが望ましいです（同じ処理で記述が別れていると見ている側が???となる））

```
redirect_to("/posts/#{params[:post_id]}")
```

**Comment by shibatadaiki** [comment]
https://github.com/ysk1180/jobmiru/blob/master/app/controllers/reply_to_comments_controller.rb
特に使ってないアクションとかもビューもありそうなので、それも消しちゃってくださいね〜

```
  # GET /reply_to_comments/1/edit
  def edit
  end
```

**Comment by shibatadaiki** [comment]
使う予定のないヘルパー、CSS、JSも消しましょう〜
（というかそもそも、作らない設定にしちゃう方が良いですね）
https://qiita.com/ko_coon/items/318516535442f47991d7

![2018-01-30 13 57 35](https://user-images.githubusercontent.com/25131575/35548849-8b006910-05c5-11e8-8f4b-f89bdb70b53a.png)

**Comment by shibatadaiki** [comment]
has_many,belongs_to,validatesの配置がバラバラなので、
それぞれ整理してあげた方が良いです。

![2018-01-30 14 02 02](https://user-images.githubusercontent.com/25131575/35548997-78e39ad0-05c6-11e8-8012-e75aa399de03.png)

**Comment by shibatadaiki** [comment]
丁寧なコメントは非常に素晴らしいですが、ここまではいらないかも？
（nameのバリデーション設定とかは、validates :name, presence: true,って見ればわかるので）
（コメントは一目で理解の難しいような記述に説明として書いてあげるのが良いと思います！）

![2018-01-30 14 06 15](https://user-images.githubusercontent.com/25131575/35549066-f243b630-05c6-11e8-9ec3-04d6ae6c33c3.png)

**Comment by shibatadaiki** [comment]
https://github.com/ysk1180/jobmiru/blob/master/db/seeds.rb

動作確認用のseedファイルも早いうちから作ってあげられると良いですね！

**Comment by shibatadaiki** [comment]
コードの詳細なレビューはもう少し機能が出来上がってからの方が良いかと思うので、とりあえず今回はこのくらいが言いたいことになります！
（Railsでアプリを作成する時の準備や記述の基本が主な指摘になりました。コードの書き方の基本的な書き方とかは現状そこまで気になりませんでした！強いて言えばコメントがちょっと多い感じでした。後インデントには注意しながら進めていってください( 'ω' )）

こちらのレビューにつきまして何かわからないことや確認したいことなどありましたらいつでもご連絡くださいm(__)m

**Comment by shibatadaiki** [comment]
コードを書く際の注意点

・Gemfileはコメント行をあらかじめ消しておくこと
・改行は意味のある単位で行なった方がみやすいため、そうすること
・Rspecを使うならtestディレクトリは消しておく
・意味のない空行は消しておく
・ロケット記法は使わないこと
・変数やアソシエーション名は、機能に関連した名前づけを心がけ、good_answersのようにスネークケースできちんと単語を分けること
・省略した命名は基本的に使わない(意味を予測しづらいため)
・createでrespond_toを使わなくなったのであればコメントアウトではなく削除をしておくこと
・privateより下の行はprivateと同じレベルのインデントにする
・ストロングパラメータに関するコメントは基本的に不要(コードを見ればわかるため)
・updateなどの記述の際、バリデーションが発火した時の処理も考慮しておくこと。
（レンダリングするviewが見つけられなくてエラーになったりしないように注意する）
・共同開発の場合、コミットメッセージは何をしたかがちゃんとわかるものをつけること

# NG
:hoge => true

# OK
hoge: true
・インデントは必ず綺麗につける

Rubyはスペース2つをインデントのルールにする慣習がある
Railsのコーディング規約、Rubyのコーディング規約は勉強になる(非公式ですが)
https://github.com/cookpad/styleguide/blob/master/ruby.ja.md
https://github.com/satour/rails-style-guide/blob/master/README-jaJA.md
・設定を一つだけ切り出したルーティングを設定したい場合などは
onオプションのcollectionとmemberを使うことを考える

resources :questions do
  get :search, on: :collection
end
・不要なcssやjsのファイルは削除しておくこと（ディレクトリ内の見通しがよくなるため）

cssはSMACSSやBEMといった設計手法があるので、それを考えて見るのはいいかも
SMACSS: https://app.codegrid.net/entry/smacss-1
BEM: https://app.codegrid.net/entry/bem-basic-1
config/application.rbでassetsの自動生成の抑制もできる
config.generators do |g|
  # その他generator設定
  g.assets     false
  g.helper     false
end
・スタイルは基本classに当てた方がよい。要素セレクタにスタイルを当てると影響度が大きくなる。

・db周りは、全体的に制約をしっかりつけることを心がけること
（ただし、どこまで制約で縛るかを作りたい機能と照らし合わせ、都度確認をする必要はある）
（例えばanswerに外部キー制約が付ける場合、ユーザーが削除されたら、そのユーザーが回答していたanswerも消える設計をしている認識で良いのか？という具合）

・application.rbでrails g実行時にassets周りのファイルを生成しない設定をしておくとよい

・scaffoldで生成されるcssは予期せぬ影響があるかもしれないため、基本的に削除しておくこと。また、jsonなどを使用しないのであればrespond_to周りは消しておいた方が良い。

・privateの下にクラスメソッドを定義してもprivateなメソッドにならないので注意
* 参考：http://blog.agile.esm.co.jp/entry/2016/09/30/171444
* クラスメソッドをプライベート化するためにはこんなかんじ

**Comment by shibatadaiki** [comment]
アプリケーションの設定の注意点

・アプリケーションを作成する際、.envの設定は基本的に最初に済ませておくこと
・タイムゾーンの設定は基本的に日本にしておくこと

```
config/application.rb

config.time_zone = 'Tokyo'
config.active_record.default_timezone = :local
```

・ログレベルはinfoにしておくこと（本番環境でデバッグ情報を出すとLogで容量が圧迫される
ため）

```
config/production.rb

config.log_level = :info
```

**Comment by norotime** [comment]
@ysk1180 修正が完了してたら、このイシューは自分でクローズしてくださいね！
