### ISSUE TITLE
重複しているメソッドを修正検討する

### ISSUE THREAD

**Issue by norotime** [ysk1180/jobmiru#11]
https://github.com/ysk1180/jobmiru/blob/5db9f7a5c00109284d952f562748e8abe05a58fa/app/controllers/wants_controller.rb#L11

@ysk1180 ここでメソッドが重複記述されている理由はなんでしたっけ？？

**Comment by ysk1180** [comment]
@norotime 
1度目のset_wantは次の行でdestroyするために@wantにセットするため。
2度目のset_wantは、@want=nilをセットするためです。（@want = nil という記載でも同じことなので、シンプルな @want = nil の方がいいような気もしてきました。）

**Comment by norotime** [comment]
@ysk1180 同じメソッドを違う意味合いで使うのは、混乱のものです。ミスリードすることもあるため、改善したいですね。

**Comment by ysk1180** [comment]
@norotime おっしゃる通りです。混乱する可能性があるため、シンプルな形へ修正します。
