### ISSUE TITLE
CSSはアセットパイプラインを通す

### ISSUE THREAD

**Issue by norotime** [ysk1180/jobmiru#16]
https://github.com/ysk1180/jobmiru/blob/5db9f7a5c00109284d952f562748e8abe05a58fa/app/views/layouts/application.html.erb#L13

@ysk1180 このファイルは、どうしてここに書いていますか？

マニフェストファイルで読み取り、アセットパイプラインを通しているのではないでしょうか？
https://github.com/ysk1180/jobmiru/blob/5db9f7a5c00109284d952f562748e8abe05a58fa/app/assets/stylesheets/bootstrap-social.css

**Comment by ysk1180** [comment]
マニュフェストファイル、アセットパイプラインについて理解できていませんでした。。。指摘していただき、ある程度理解することができました！

**Comment by norotime** [comment]
@ysk1180 Railsの基本機能のため、ぜひともマスターしてください。

**Comment by norotime** [comment]
Sprocketsの仕様を学習すると良いでしょう。公式ドキュメントが一番詳しいですよ。
https://github.com/rails/sprockets
