### ISSUE TITLE
DICコードチェック基礎編に準拠させる

### ISSUE THREAD

**Issue by norotime** [ysk1180/jobmiru#17]
`コードの可読性`

- [x] Gemfileはコメント行をあらかじめ消しておくこと

- [x] 改行は意味のある単位で行なった方がみやすいため、そうすること		

- [x] 意味のない空行は消しておく		

- [x] ロケット記法は使わないこと（ `NG :hoge => true` 、`OK  hoge: true`）		

- [x] 変数やアソシエーション名は、機能に関連した名前づけを心がけ、good_answersのようにスネークケースできちんと単語を分けること		

- [x] 省略した命名は基本的に使わない(意味を予測しづらいため)		

- [x] createでrespond_toを使わなくなったのであればコメントアウトではなく削除をしておくこと		

- [x] privateより下の行はprivateと同じレベルのインデントにする		

- [x] ストロングパラメータに関するコメントは基本的に不要(コードを見ればわかるため)		
  （updateなどの記述の際、バリデーションが発火した時の処理も考慮しておくこと。）
  （更新に失敗した際、レンダリングするviewが見つけられなくてエラーになったりしないように注意する）

- [x] インデントは必ず綺麗につける
（Rubyはスペース2つをインデントのルールにする慣習がある、Railsのコーディング規約、Rubyのコーディング規約は勉強になる。非公式ですが）
https://github.com/cookpad/styleguide/blob/master/ruby.ja.md 、
https://github.com/satour/rails-style-guide/blob/master/README-jaJA.md

`実装方法`

- [x] スタイルは基本classに当てた方がよい。要素セレクタにスタイルを当てると影響度が大きくなる。		
(scaffoldで生成されるcssは予期せぬ影響があるかもしれないため、基本的に削除しておくこと。)
(また、jsonなどを使用しないのであればrespond_to周りは消しておいた方が良い。)

`無駄のないアプリケーション構成`

- [x] Rspecを使うならtestディレクトリは消しておく		

- [x] 不要なcssやjsのファイルは削除しておくこと（ディレクトリ内の見通しがよくなるため。config/application.rbでassetsの自動生成の抑制もできる）		

`初期設定`

- [x] アプリケーションを作成する際、.envの設定は基本的に最初に済ませておくこと		

- [x] タイムゾーンの設定は基本的に日本にしておくこと
```
config/application.rbにて
config.time_zone = 'Tokyo'
config.active_record.default_timezone = :local　の設定をする
```

`Gitの使い方。共同作業の際の注意点`

- [x] イシュー、プルリク、コミットは必ず意味のある名前にすること。コミットは小さく一つ一つの機能ごとにするのが望ましい。

**Comment by norotime** [comment]
@ysk1180 チェックリストのため、できていたら、チェックしておいてくださいね！便利ですよ。

**Comment by ysk1180** [comment]
@norotime まとまっていてすごくありがたいです！「privateより下の行はprivateと同じレベルのインデントにする」については初めて聞きました！

**Comment by norotime** [comment]
@ysk1180 はい〜！自分なりのチェック表を作ってみてくださいーー。
