### ISSUE TITLE
DBMSハングを防止するために SQLクエリ取得上限レコードを設定する

### ISSUE THREAD

**Issue by norotime** [ysk1180/jobmiru#9]
モデル全体に適用するか、個々のモデルに適用させるか、判断して実装をお願いします。
データ量まで想定してください。

ヒントは、
scope
limit
です。

**Comment by norotime** [comment]
.allでレコード取得して本当に大丈夫なのか？は想像してみてください。
100万件レコードがあるかもしれませんよー。

**Comment by ysk1180** [comment]
@norotime 投稿・コメント・コメントへの返信をそれぞれ一旦100件に設定しました。投稿は検索で絞り込んだ後に100件表示できるようになっています。
